# Generated by Django 5.2.7 on 2026-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_enrollment'),
        ('user', '0011_alter_instructorprofile_id_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passkey',
            field=models.CharField(help_text='Put PassKey', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='used_passkey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='course_enro_student_64d6ab_idx'),
        ),
    ]
