# Generated by Django 6.0.1 on 2026-01-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_questionchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='question_type',
        ),
    ]
