# Generated by Django 6.0.1 on 2026-01-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_questionchoice_is_correct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questionChoice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='Question_list',
            field=models.CharField(blank=True, choices=[('Multiple Choice', 'Multiple Choice'), ('True/False', 'True/False'), ('Short Answer', 'Short Answer')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
