# Generated by Django 6.0.1 on 2026-01-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_question_calories_burned_question_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Quiz',
            new_name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='Question_list',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TF', 'True / False'), ('SA', 'Short Answer')], default='MC', max_length=2),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
