# Generated by Django 5.2.7 on 2026-03-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quiz_is_active_alter_answer_id_alter_question_id_and_more'),
        ('user', '0011_alter_instructorprofile_id_alter_studentprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_quiz_attempts', to='user.instructorprofile'),
        ),
    ]
