# Generated by Django 5.2.7 on 2026-03-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_quiz_is_active_alter_answer_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=dict, help_text='Store selected answer IDs per question'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='score_override',
            field=models.PositiveIntegerField(blank=True, help_text='Manual override for score', null=True),
        ),
    ]
