# Generated by Django 5.2.7 on 2026-03-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_quizattempt_answers_quizattempt_edited_at_and_more'),
        ('quiz', '0019_quizattempt_answers_quizattempt_score_override'),
    ]

    operations = [
    ]
