# Generated by Django 5.2.7 on 2026-04-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_add_enumeration_question_type'),
        ('quiz', '0022_alter_quiz_options'),
    ]

    operations = [
    ]
