# Generated by Django 5.2.7 on 2026-04-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_merge_20260409_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
    ]
