# Generated by Django 6.0.1 on 2026-04-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_answer_id_alter_question_id_alter_quiz_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_format',
            field=models.CharField(choices=[('exact', 'Exact case'), ('ignore', 'Ignore case'), ('upper', 'All uppercase'), ('lower', 'All lowercase'), ('capitalize', 'Capitalize')], default='exact', help_text='How to handle case sensitivity for text answers', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
