# Generated by Django 5.2.7 on 2026-04-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_answer_id_alter_question_id_alter_quiz_id_and_more'),
        ('quiz', '0029_alter_answer_id_alter_question_id_alter_quiz_id_and_more'),
    ]

    operations = [
    ]
