# Generated by Django 5.2.7 on 2026-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_quizactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizactivitylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
