# Generated by Django 5.2.11 on 2026-02-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_created_at_alter_course_updated_at'),
        ('user', '0006_instructorprofile_full_name_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='assigned_courses',
            field=models.ManyToManyField(related_name='instructors', to='course.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='students', to='course.course'),
        ),
    ]
