# Generated by Django 5.2.7 on 2026-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_securityauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='securityauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
