# Generated by Django 5.2.7 on 2026-04-25 08:20

from django.db import migrations


def _column_exists(schema_editor, table_name, column_name):
    cursor = schema_editor.connection.cursor()
    try:
        cursor.execute(f'PRAGMA table_info("{table_name}")')
        return any(row[1] == column_name for row in cursor.fetchall())
    finally:
        cursor.close()


def _conditionally_remove_report_fields(apps, schema_editor):
    Report = apps.get_model('user', 'Report')
    table_name = Report._meta.db_table
    for field_name in ('reporter_email', 'reporter_role', 'reporter_username'):
        if _column_exists(schema_editor, table_name, field_name):
            field = Report._meta.get_field(field_name)
            schema_editor.remove_field(Report, field)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_report_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _conditionally_remove_report_fields,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='report',
                    name='reporter_email',
                ),
                migrations.RemoveField(
                    model_name='report',
                    name='reporter_role',
                ),
                migrations.RemoveField(
                    model_name='report',
                    name='reporter_username',
                ),
            ],
        ),
    ]
